version: "3.9"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - PORT=5000
      - NODE_ENV=production
      - CORS_ORIGIN=http://localhost:8080
    ports:
      - "5000:5000"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    depends_on:
      - api
    ports:
      - "8080:80"
    restart: unless-stopped
