name: Generate Code Docs
on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"
      - "frontend/**"
      - "tools/gendocs.*"
      - "tools/gendocs.config.json"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
      - run: npm run docs:code
      - name: Commit docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/code docs/CODE_MAP.md
          git commit -m "chore(docs): auto-generate per-file MD" || echo "No changes"
          git push
